server:
  applicationConnectors:
    - type: http
      port: 6000
  adminConnectors:
    - type: http
      port: 6001
#
# Database configuration
#
database:
  driverClass: com.mysql.jdbc.Driver
  user: ${ECHO_DB_USER}
  password: ${ECHO_DB_PASSWORD}
  url: ${ECHO_DB_URL}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* EchoService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  initialSize: ${ECHO_DB_CP_INITIAL_SIZE:-2}
  minSize: ${ECHO_DB_CP_MIN_SIZE:-2}
  maxSize: ${ECHO_DB_CP_MAX_SIZE:-4}
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

allowedPeers:
  credentialFile: allowed-peers.properties
  encryptor: BASIC

metrics:
  frequency: ${DATADOG_FREQUENCY:-1 minute}
  reporters:
    - type: datadog
      tags: [${DATADOG_TAGS:-""}]
      excludes:
        - ch.qos.logback
        - io.dropwizard.jetty.MutableServletContextHandler
        - org.eclipse.jetty.util.thread.QueuedThreadPool
        - io.dropwizard.jetty.MutableServletContextHandler
        - org.skife.jdbi.v2.DBI.raw_sql
        - io.dropwizard.db.ManagedPooledDataSource
        - sql.raw
      useRegexFilters: true
      transport:
        type: udp
        statsdHost: ${DATADOG_HOST:-localhost}
        port: ${DATADOG_PORT:-8125}
        prefix: ${DATADOG_PREFIX:-""}
        retryingLookup: true
